name: ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-plugin:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: plugin
    strategy:
          matrix:
            node-version: [18.20.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm --filter @orimdominic/genkitx-mongodb install
      - name: Build plugin
        run: pnpm run build
