name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: "ubuntu-latest"
    strategy:
          matrix:
            node-version: [18.20.8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          package-manager-cache: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Debug OIDC
        run: |
          cat packages/genkitx-mongodb/package.json
      - name: Create PR and publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
